name: Build Spotify EQ

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          

      - name: Build
        run: |
          export THEOS=$HOME/theos
          brew install ldid 
          make
      

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: SpotifyEQ10
          path: .theos/obj/debug/SpotifyEQ10.dylib
